language: cpp
compiler: 
  - gcc
  - clang
os:
  - linux
  - osx
sudo: true
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install gcc-multilib g++-multilib libstdc++6-4.6-pic; fi
script:
  - cd dlls
  - make -j2
